### ISSUE TITLE
Current live sample site gives error

### ISSUE THREAD

**Issue by svdoever** [ampproject/amp-publisher-sample#66] opened 2017-05-07 10:12 UTC
On the sample site after first click I get the error below on chrome Version 58.0.3029.96 (64-bit):

Uncaught Error: No ampdoc found for [object HTMLElement]
    at va (https://cdn.ampproject.org/shadow-v0.js:7:358)
    at ta.f.createError (https://cdn.ampproject.org/shadow-v0.js:4:36)
    at xf.getAmpDoc (https://cdn.ampproject.org/shadow-v0.js:129:512)
    at HTMLElement.b.connectedCallback (https://cdn.ampproject.org/shadow-v0.js:161:11)
    at https://cdn.ampproject.org/rtv/001493770802531/v0/amp-carousel-0.1.js:21:318
    at Array.forEach (native)
    at S.push.f.f.buildSlides (https://cdn.ampproject.org/rtv/001493770802531/v0/amp-carousel-0.1.js:21:142)
    at S.push.f.f.buildCarousel (https://cdn.ampproject.org/rtv/001493770802531/v0/amp-carousel-0.1.js:16:326)
    at S.push.f.f.buildCallback (https://cdn.ampproject.org/rtv/001493770802531/v0/amp-carousel-0.1.js:11:465)
    at HTMLElement.b.build (https://cdn.ampproject.org/shadow-v0.js:155:514)

**Comment by dvoytenko** [comment] 2017-05-08 17:46
Sebastian/Will, do you know where/why this error is happening?

**Comment by choumx** [comment] 2017-07-25 16:30
I believe this is a dupe of https://github.com/ampproject/amphtml/issues/9291.

**Closed by choumx** 2017-07-25 16:30 UTC
Labels: duplicate
